### ISSUE TITLE
After reading your article EO-PSI, I want to reproduce the experiment, but encountered some problems

### ISSUE THREAD

**Issue by WandQ** [nitrogl/eo-psi#3]
Hi! Metere,

After reading your article EO-PSI, I benefited a lot. I downloaded the code that you uploaded on github, and configured the environment on Ubuntu. I have the following problems when trying to run:

(1)Is the sets data in your experiment randomly generated in the program?

(2)What are procedures zzrndgen hbtest bptest eopsisimul cherpars used for testing?  Does their name have any meaning?

(3)I tried to run your program, but I don't know how to enter it. Could you give me some examples of the ubuntu command line, how to run the program when the set size of both sides is 2^20. And  "-B: number of bits in plain sets" in the program means that the size of the sets data is 2^b?
![1609652042(1)](https://user-images.githubusercontent.com/56994734/103472431-75cb7c80-4dc8-11eb-9fdc-b11664fb8511.jpg)
I sent you an email with the above content, and I look forward to your reply.
Thank you!!

**Comment by WandQ** [comment]
root@d5045ec134ca:/workspace/eo-psi/build/src/test# ./eopsisimul -b 128 -p 128 -k 1172 -l 100 -n 65536 -r 32768
./eopsisimul. Random field size set to prime number 208877927325220796392988832162917744531 (128).
 --- Settings ------------------------
         Number of buckets: 1172
       Size of each bucket: 100
            Plain set bits: 128
                Field size: 208877927325220796392988832162917744531 (128 bits)
Number of elements per set: 65536
   Minimum common elements: 32768
 -------------------------------------
0. Generating minimum common data required 31.919 ms
0. Generating random data for A required 31.614 ms
0. Generating random data for B required 31.222 ms
Alice. Blinding......root@d5045ec134ca:/workspace/eo-psi/build/src/test#

The above is the situation I encountered when I was running. It seemed that it stopped before it was completely finished. Is there any problem with the parameters I entered? Looking forward to your reply.
Thank you

**Comment by nitrogl** [comment]
Hi WangQ,

Thanks for your interest. In light of your concerns, I have pushed some bugfixes.

1. data are randomly generated using zzrndgen.
2. I added some description of the binaries in the README.md file.
3. To have an idea of what arguments to use, you can inspect in the script "/runtests.sh"

I hope the bugfixes and hints here will be enough to let you have a better experience.

**Comment by WandQ** [comment]
With your help, I have been able to run your program, thank you very much.
